version: "3.3"
services:

    front:
        volumes:
            - ./front:/usr/src/app
        working_dir: /usr/src/app
        command: bash -c "npm install && npm run build --production"

    nginx:
        image: nginx
        restart: always
        volumes:
            - ./docker/nginx/prod.conf:/etc/nginx/conf.d/app.conf
            - ./front/dist/:/var/www/

