version: "3.3"
services:

    api:
        image: node
        restart: always
        volumes:
            - ./api:/usr/src/app
        working_dir: /usr/src/app
        command: bash -c "npm install && npm run start"
        expose:
            - 3000

    front:
        image: node
        volumes:
            - ./front:/usr/src/app
        working_dir: /usr/src/app

    nginx:
        image: nginx
        ports:
            - 80:80
        depends_on:
            - api

    db:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: toor
            MONGO_INITDB_DATABASE: optimize
        volumes:
            - ./docker/db/init.js:/docker-entrypoint-initdb.d/init.js:ro
        expose:
            - 27017

