version: "3.3"
services:

    front:
        restart: always
        expose:
            - 4200
        volumes:
            - ./front:/usr/src/app
        command: bash -c "npm install && npm run start"

    nginx:
        volumes:
            - ./docker/nginx/dev.conf:/etc/nginx/conf.d/app.conf

